name: Test
on: [push]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.8
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.1" # Твоя версія зі скріншота
          bundler-cache: true

      - name: Install Node & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/purrpurr_test
          RAILS_ENV: test
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails test
